services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\VideoPlatforms\:
        resource: '../../*'
        exclude: '../../{Exception,Video,BecklynVideoPlatformsBundle.php}'

    Becklyn\VideoPlatforms\Platform\VideoPlatforms:
        $platforms: !tagged_locator { tag: becklyn.video-platform, default_index_method: getKey }
